---
title: "Decision Tree"
author: "Surendra Kumar Dattatrey"
date: "12 May 2018"
output: html_document
---

```{r setup, include=FALSE }
library("ggplot2")
library("tree")
library("caret")
library("ROCR")
library("data.table")
library("dplyr")
library("pscl")
library("MASS")
library("e1071")
library("rpart.plot")
```

Data Cleaning Process

```{r}
myData = read.csv("C:\\Users\\Yash\\Desktop\\ISB Documents\\Capstone Project\\Data\\Raj Data\\Raj_data_for_EDA.csv",header=TRUE)

######################################################################
############# Data Cleaning ##########################################
######################################################################


## Removing last columns
myData <- myData[,-54]
myData <- myData[,-54]
myData <- myData[,-54]
myData <- myData[,-54]
myData <- myData[,-54]
myData <- myData[,-54]

## Removing first columns
myData <- myData[,-1]
myData <- myData[,-1]
a <- as.data.frame(myData)
b <- as.data.table(myData)

# Confirm dimensionality
dim(a) 
dim(b) 
# Unique rows using all columns
dim(unique(a))  
dis_mydata <- as.data.frame(unique(a))
#dim(unique(b))  
dis_mydata_u <- as.data.table(unique(b))

#dis_mydata %>%
#  select(dis_mydata$Dlr.Code, dis_mydata$Tehsil, dis_mydata$DSE )

dis_mydata_subset <- dis_mydata[, c(5,14,18,23,29,35)]

dis_mydata_subset$Status_der<-0

dis_mydata_subset$Status_der <- ifelse(dis_mydata_subset$Status > 3 |dis_mydata_subset$Status < 3 , 0, 1)

dis_mydata_subset$Status_der <- as.factor(dis_mydata_subset$Status_der)


dis_mydata_subset <- dis_mydata_subset[,-6]


######################################################################
############# Decision Tree ####################################
######################################################################
############# Splitting data between Train and Test ##################

dt = sort(sample(nrow(dis_mydata_subset), nrow(dis_mydata_subset)*.7))
train_total<-dis_mydata_subset[dt,]
test_total<-dis_mydata_subset[-dt,]

trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)
set.seed(3333)
dtree_fit <- train(Status_der ~ ., data = train_total, method = "rpart",
                   parms = list(split = "information"),
                   trControl=trctrl,
                   tuneLength = 10)

prp(dtree_fit$finalModel, box.palette = "Reds", tweak = 1.2)

test_pred <- predict(dtree_fit, newdata = test_total)
confusionMatrix(test_pred, test_total$Status_der )  #check accuracy


```



```{r}
test_pred <- predict(dtree_fit, newdata = test_total)
confusionMatrix(test_pred, test_total$Status_der )  #check accuracy

```
